apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-echo
  namespace: default
  labels:
    app: eks-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-echo
  template:
    metadata:
      labels:
        app: eks-echo
    spec:
      containers:
      - name: eks-echo
        image: gcr.io/istio-testing/app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: eks-echo
  namespace: default  
  labels:
    app: eks-echo
spec:
  selector:
    app: eks-echo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP